version: '3.8'
services:
    mongodb_container:
        build: Mongo/
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodb_data_container:/data/db
        networks:
            app_net:
               aliases:
                   - mongodb_container
    flask_container:
        build : Flask/
        depends_on:
            - mongodb_container
        deploy:
            replicas: 2
        environment:
            MONGO_INITDB_ROOT_USERNAME : mongoadmin 
            MONGO_INITDB_ROOT_PASSWORD  : secret 
            MONGODB_HOST :  mongodb_container
            FLASK_HOST : flask_container 
        networks:
            app_net:
               aliases:  
                  - flask_container

volumes:
    mongodb_data_container:

networks:
    app_net:
