version: '2'
services:
    mongodb_container:
        build: Mongo/
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoadmin
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - app_net
    flask_container:
        build : Flask/
        depends_on:
            - mongodb_container
        environment:
            MONGO_INITDB_ROOT_USERNAME : mongoadmin 
            MONGO_INITDB_ROOT_PASSWORD  : secret 
            MONGODB_HOST :  mongodb_container
           
        ports :
            - 5000:5000
        networks:
            - app_net

volumes:
    mongodb_data_container:

networks:
    app_net: